version: '3.9'

networks:
  ticket-network:
    driver: bridge
services:
  ticket-pg:
    image: postgres:16.2-alpine
    container_name: ticket-pg
    networks:
      - ticket-network
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_password
      POSTGRES_DB: ticket_db
    volumes:
      - ./data-db:/var/lib/postgresql/data
    ports:
      - 5444:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d ticket_db -U ticket_user' ]
      interval: 10s
      timeout: 5s
      retries: 5
  ticket-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticket-app:latest
    container_name: ticket-app
    networks:
      - ticket-network
    restart: on-failure
    depends_on:
      ticket-pg:
        condition: service_healthy
    ports:
      - 8080:8080
