server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://ticket-pg:5432/ticket_db
    username: ticket_user
    password: ticket_password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
